baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'DADESS'

header:
  services:
    en: Services
    es: Servicios
    ca: Serveis
  team:
    en: Team
    es: Equipo
    ca: Equip
  projects:
    en: Featured Projects
    es:
    ca: Casos d'èxit
  testimonials:
    en: Testimonials
    es: Testimonios
    ca: Testimonis
  contact:
    en: Contact
    es: Contacto
    ca: Contacte

team_page:
  title:
    en: Core Team
    es:
    ca: L'equip impulsor
  call:
    en: 
    es:
    ca: "Treballem per fer créixer el vostre projecte mitjançant les dades, algoritmes i la consciència social."
  organizers:
    en: Organizations
    es:
    ca: Entitats Impulsores
  org_call:
    en: 
    es:
    ca: "DADESS és un paraigua de les entitats d'economia social i solidària que tenen l'objectiu d'impulsar la digitalització del sector i fomentar l'ús de dades per millorar les seves operacions. Les entitats que formen part de la comunitat DADESS, independentment i col·laborativament proporcionen serveis i executen projectes per aquesta finalitat."

organizers:
  - name: 'Coopdevs'
    image: '/images/team/coopdevs_without_slogan.svg'
    link: 'https://coopdevs.org/'
#  - name: 'LabCoop'
#    image: '/images/team/labcoop.jpg'
#    link: 'http://labcoop.coop/'
  - name: 'femProcomuns'
    image: '/images/team/femProcomuns_logo.png'
    link: 'https://femprocomuns.coop/'
  - name: 'Col·lectivaT'
    image: '/images/team/collectivat_logo.png' 
    link: 'https://collectivat.cat'

projects:
  title:
    en: Featured projects
    es:
    ca: Casos d'èxit
  call:
    en: "Voluptatem reprehenderit voluptatem sit possimus quaerat alias odit et. Repellat consequatur et saepe placeat consequuntur sit fuga illo. Sit dolores ab ut assumenda omnis sapiente voluptas ipsa."
    es:
    ca: "Com una entitat dedicada a la inclusió i la innovació social, apliquem diverses metodologies de ciència de dades als projectes de l'ESS. Aquí podeu trobar alguns exemples dels nostres casos d'èxit de les solucions que havíem implementat fins ara."

collections:
  services:
    output: true
    permalink: /serveis/:path/
  team:
    output: true
    permalink: /equip/:path/
  testimonials:
    output: true
    permalink: /testimonis/:path/

signup:
  title:
    en: Discover
    es:
    ca: Informeu-vos
  call:
    en:
    es:
    ca: "Si voleu estar al dia sobre els usos innovadors de les dades i la intel·ligència empresarial per l'economia solidària, deixeu el vostre correu electrònic per subscriure al nostre butlletí"
  mini_call:
    en: Subscribe to our newsletter
    es:
    ca: Subscriu-te al nostre butlletí
  subscribe:
    en:
    es:
    ca: Subscriu-te
  placeholder:
    en: email address
    es:
    ca: "Correu electrònic"

contribute:
  title:
    en: Contribute
    es:
    ca: Contribuïu
  call:
    en:
    es:
    ca: "Voluptatem reprehenderit voluptatem sit possimus quaerat alias odit et. Repellat consequatur et saepe placeat consequuntur sit fuga illo. Sit dolores ab ut assumenda omnis sapiente voluptas ipsa."
  button:
    en:
    es:
    ca: Col·laboreu

defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
     image: true

strings:
  email:
    en: Email
    es:
    ca: "Correu electrònic"
  adress:
    en: Adress
    es:
    ca: L'adreça

sass:
  style: compact # possible values: nested expanded compact compressed

google_analytics_id: null

plugins:
  - jekyll-environment-variables
