baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'DADESS'

header:
  services:
    en: Services
    es: Servicios
    ca: Serveis
  team:
    en: Team
    es: Equipo
    ca: Equip
  testimonials:
    en: Testimonials
    es: Testimonios
    ca: Testimonis
  contact:
    en: Contact
    es: Contacto
    ca: Contacte

collections:
  services:
    output: true
    permalink: /services/:path/
  team:
    output: true
    permalink: /team/:path/
  testimonials:
    output: true
    permalink: /testimonials/:path/

signup:
  title:
    en: Discover
    es:
    ca: Informeu-vos
  call:
    en:
    es:
    ca: "Si voleu estar al dia sobre els usos innovadors de les dades i la intel·ligència empresarial per l'economia solidària, deixeu el vostre correu electrònic per subscriure al nostre butlletí"
  mini_call:
    en: Subscribe to our newsletter
    es:
    ca: Subscriu-te al nostre butlletí
  subscribe:
    en:
    es:
    ca: Subscriu-te
  placeholder:
    en: email address
    es:
    ca: "Correu electrònic"

contribute:
  title:
    en: Contribute
    es:
    ca: Contribuïu
  call:
    en:
    es:
    ca: "Voluptatem reprehenderit voluptatem sit possimus quaerat alias odit et. Repellat consequatur et saepe placeat consequuntur sit fuga illo. Sit dolores ab ut assumenda omnis sapiente voluptas ipsa."
  button:
    en:
    es:
    ca: Col·laboreu

defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
     image: true

sass:
  style: compact # possible values: nested expanded compact compressed

google_analytics_id: null

plugins:
  - jekyll-environment-variables
