title: "Dades i algoritmes pel consum responsable i la inclusió social"
description: "Treballem en el mercat social amb criteris socials per a que els projectes d'economia solidària i social puguin creixer"
